#konfigurujemy połączenie z bazą danych
spring:
  datasource:
    url: jdbc:postgresql://localhost:54329/library
    username: library_user
    password: library_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: library
